const GAME_STATE_CHOOSING_CARDS = "GAME_STATE_CHOOSING_CARDS";
const GAME_STATE_REVEALING_CARDS = "GAME_STATE_REVEALING_CARDS";
const GAME_STATE_ALL_CARDS_CHOOSEN = "GAME_STATE_ALL_CARDS_CHOOSEN";
const GAME_STATE_NEW_ROUND = "GAME_STATE_NEW_ROUND";
const NEW_CARD_VALUE = "NEW_CARD_VALUE";

module.exports = {
  GAME_STATE_REVEALING_CARDS,
  GAME_STATE_CHOOSING_CARDS,
  GAME_STATE_ALL_CARDS_CHOOSEN,
  GAME_STATE_NEW_ROUND,
  NEW_CARD_VALUE
}