const GAME_STATE_CHOOSING_CARDS = "GAME_STATE_CHOOSING_CARDS";
const GAME_STATE_REVEALING_CARDS = "GAME_STATE_REVEALING_CARDS";
const GAME_STATE_ALL_CARDS_CHOOSEN = "GAME_STATE_ALL_CARDS_CHOOSEN";

module.exports = {
  GAME_STATE_REVEALING_CARDS,
  GAME_STATE_CHOOSING_CARDS,
  GAME_STATE_ALL_CARDS_CHOOSEN
}